name: Refactor (internal)
description: For internal use only.
labels: ['type:refactor', 'status:requirements', 'priority-5-triage']
body:
  - type: textarea
    id: describe-the-proposed-refactor
    attributes:
      label: Describe the proposed refactor.
      description: 'Do not report any security concerns here. Email [renovate-disclosure@whitesourcesoftware.com](mailto:renovate-disclosure@whitesourcesoftware.com) instead.'
    validations:
      required: true
